# -*- coding: utf-8 -*-
"""working version 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnEqPC1HkeEfDmt5UIK1kiyXk8nAVK-D
"""

!pip install langgraph langchain sentence-transformers openrouter

!pip install -U langchain langgraph langchain-openai sentence-transformers openrouter

import os
import getpass
from langchain_openai import ChatOpenAI
from langchain.schema import HumanMessage
from sentence_transformers import SentenceTransformer

# Ask for OpenRouter key
openrouter_key = getpass.getpass(" Enter your OpenRouter API key")

# Set key + OpenRouter endpoint
os.environ["OPENAI_API_KEY"] = openrouter_key
os.environ["OPENAI_BASE_URL"] = "https://openrouter.ai/api/v1"

# LLM & Embedder
llm = ChatOpenAI(model="openai/gpt-3.5-turbo", temperature=0)
embedder = SentenceTransformer("all-MiniLM-L6-v2")

memory = {
    "core": [],
    "episodic": [],
    "semantic": [],
    "procedural": [],
    "resource": [],
    "vault": []
}

def core_memory_manager(text):
    if "name" in text or "like" in text:
        memory["core"].append(text)
        return "Core Memory"

def episodic_memory_manager(text):
    if "today" in text or "did" in text:
        memory["episodic"].append(text)
        return "Episodic Memory"

def semantic_memory_manager(text):
    if "means" in text or "is defined as" in text:
        memory["semantic"].append(text)
        return "Semantic Memory"

def procedural_memory_manager(text):
    if "steps to" in text or "how to" in text:
        memory["procedural"].append(text)
        return "Procedural Memory"

def resource_memory_manager(text):
    if "pdf" in text or "document" in text:
        memory["resource"].append(text)
        return "Resource Memory"

def vault_memory_manager(text):
    if any(w in text.lower() for w in ["email", "password", "api key"]):
        memory["vault"].append(text)
        return "Vault Memory"

def meta_router(state):
    user_input = state["input"]

    # Memory decision
    decisions = {
        "core": core_memory_manager(user_input),
        "episodic": episodic_memory_manager(user_input),
        "semantic": semantic_memory_manager(user_input),
        "procedural": procedural_memory_manager(user_input),
        "resource": resource_memory_manager(user_input),
        "vault": vault_memory_manager(user_input)
    }

    detected = [k for k, v in decisions.items() if v is not None]
    mem_type = detected[0] if detected else "none"

    # Generate LLM-based response
    message = f"User prompt: {user_input}\nWhich memory type does it belong to and why?"
    response = llm.invoke([HumanMessage(content=message)]).content

    return {"result": f"{response} [Stored in {mem_type.capitalize()} Memory]" if mem_type != "none" else response}

from sentence_transformers import util

def retrieve_memory(state):
    query = state["input"].lower().replace("get:", "").strip()
    query_emb = embedder.encode(query, convert_to_tensor=True)

    matches = {}
    for mem_type, entries in memory.items():
        if not entries:
            matches[mem_type] = []
            continue

        entry_embs = embedder.encode(entries, convert_to_tensor=True)
        cos_scores = util.cos_sim(query_emb, entry_embs)[0]
        matched = [entries[i] for i in range(len(entries)) if cos_scores[i] > 0.6]
        matches[mem_type] = matched

    return {"result": f"Retrieved from memory: {matches}"}

from langgraph.graph import StateGraph, END
from langchain_core.runnables import RunnableLambda
from typing import TypedDict

class MemoryState(TypedDict):
    input: str
    result: str

graph = StateGraph(MemoryState)

graph.add_node("Router", RunnableLambda(meta_router))
graph.add_node("Retriever", RunnableLambda(retrieve_memory))

def entry_router(state):
    if state["input"].lower().startswith("get:"):
        return {"next": "Retriever"}
    return {"next": "Router"}

graph.add_node("EntryRouter", RunnableLambda(entry_router))
graph.set_entry_point("EntryRouter")

graph.add_conditional_edges("EntryRouter", lambda state: state["next"])
graph.add_edge("Router", END)
graph.add_edge("Retriever", END)

memory_graph = graph.compile()
print(" Memory Graph (Version 2 - LLM Integrated) is Ready!")

!pip install gradio --quiet
import gradio as gr

# Gradio UI function
def gradio_fn(user_input):
    try:
        out = memory_graph.invoke({"input": user_input})
        return out["result"]
    except Exception as e:
        return f" Error: {str(e)}"

demo = gr.Interface(
    fn=gradio_fn,
    inputs=gr.Textbox(lines=2, placeholder="Ask or Store a memory (e.g. 'I like pizza' or 'get:pizza')"),
    outputs="text",
    title=" MIRIX LLM Agent (Version 2)",
    description="Enter memory statements to store, or use 'get:<keyword>' to retrieve."
)

demo.launch()

import json
import csv
from tqdm import tqdm

# Load sampled prompts (JSON)
with open("/content/mirix_prompts_sampled.json", "r") as f:
    all_prompts = json.load(f)

print(f"✅ Loaded {len(all_prompts)} sampled prompts.")

# Run through memory graph
v2_sampled_outputs = []

for prompt in tqdm(all_prompts, desc="🔍 Testing Sampled Prompts"):
    try:
        out = memory_graph.invoke({"input": prompt["input"]})
        v2_sampled_outputs.append({
            "input": prompt["input"],
            "expected_type": prompt["type"],
            "output": out["result"]
        })
    except Exception as e:
        print(f"⚠️ Error for input: {prompt['input']}")
        print(str(e))
        v2_sampled_outputs.append({
            "input": prompt["input"],
            "expected_type": prompt["type"],
            "output": f"ERROR: {str(e)}"
        })

# Save results
with open("mirix_outputs_v2_sampled.json", "w") as f:
    json.dump(v2_sampled_outputs, f, indent=2)

with open("mirix_outputs_v2_sampled.csv", "w") as f:
    writer = csv.DictWriter(f, fieldnames=["input", "expected_type", "output"])
    writer.writeheader()
    writer.writerows(v2_sampled_outputs)

print("✅ Outputs saved to 'mirix_outputs_v2_sampled.json' and 'mirix_outputs_v2_sampled.csv'")